#title: Digits
#description: A template for quickly starting Next.js application development
#google_analytics:
#show_downloads: true 
#theme: jekyll-theme-merlot
remote_theme: pages-themes/hacker
#gems:
  #- jekyll-mentions
